### ISSUE TITLE
Update to DD 3.1 and TF 1.0

### ISSUE THREAD

**Issue by koblas** [claranet/terraform-datadog-monitors#1]
It would be great if you could do the update to both the Datadog and Terraform 1.0. 

ps. Issue templates would be a big addition for GitHub.

**Comment by xp-1000** [comment]
Hello @koblas

About upgrading version for terraform and datadog provider, the current code base should be compatible.
Did you meet a specific problem with these versions ?

Currently, we don't have constraint for the provider version and that is true it would be better to add it.

Regarding the terraform version itself, we still set the 0.12.26 constraint which should be the oldest version compatible if I am not wrong. I think we should avoid to upgrade this minimum version without a good reason to allow users with old terraform versions to continue to use related modules.

**Comment by koblas** [comment]
The  datadog provider 3.1 has changed  `threshold = {` to `monitor_threshold {`.  Also, it appears all of the `lifecycle` rules no longer work.

In Terraform 1.0 I noted in the common/filters the `list(...)` has been replaced with `tolist([....])`

Which basically means that if you upgrade to Terraform 1.0 this no longer works.  Most packages would pin the 12.x version on the your 3.x release versions and then have a 4.x version which was Terraform 1.0 compatible.

**Comment by xp-1000** [comment]
@koblas https://github.com/claranet/terraform-datadog-monitors/releases/tag/v4.0.0 has been released with support for datadog provider v3 and it remains compatible with terraform 0.12

**Comment by koblas** [comment]
Thanks, but still a bit disappointed that you're not supporting Terraform 1.0.

**Comment by xp-1000** [comment]
It supports Terraform >= 0.12.31 including 1.0

**Comment by koblas** [comment]
Interesting, when I tried I got an error that said.
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/219934/122939110-5528bc00-d341-11eb-9b74-4233d7081d41.png">

**Comment by xp-1000** [comment]
are you sure you use the `v4.0.0.` tag ? this `list` function has been removed in the related PR: https://github.com/claranet/terraform-datadog-monitors/pull/3/files#diff-c4f9a5a2a0532daa7985899e6b9e05df0246b2da7b84aedae790ff5405420c8aR15

**Comment by koblas** [comment]
I had missed that fix, thanks.
