### ISSUE TITLE
Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.

### ISSUE THREAD

**Issue by hlepesant** [claranet/terraform-datadog-monitors#32]
`$ terraform init
Initializing modules...
Downloading registry.terraform.io/claranet/monitors/datadog 4.1.0 for datadog-message-alerting...
- datadog-message-alerting in .terraform/modules/datadog-message-alerting/common/alerting-message

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of datadog/datadog from the dependency lock file
- Reusing previous version of hashicorp/vault from the dependency lock file
- Reusing previous version of hashicorp/template from the dependency lock file
- Installing datadog/datadog v3.12.0...
- Installed datadog/datadog v3.12.0 (signed by a HashiCorp partner, key ID FB70BE941301C3EA)
- Installing hashicorp/vault v3.7.0...
- Installed hashicorp/vault v3.7.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms
│ supported.
╵`

The provider template is deprecated since terraform 0.12, therefore it can't be pulled for ARM64 version of recent version of terraform.

**Comment by pdecat** [comment]
The solution is to replace our usage of `template_file` data source by [`templatefile` function](https://www.terraform.io/language/functions/templatefile).

https://github.com/claranet/terraform-datadog-monitors/blob/v4.2.8/common/alerting-message/main.tf#L1

**Comment by hugueslepesant** [comment]
yes and it's the objective of 
https://github.com/claranet/terraform-datadog-monitors/pull/33
