### ISSUE TITLE
Remove default team tag (or overwrite it)

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [claranet/terraform-datadog-monitors#50]
Hi,

First of all, thank you for this great, well done and complete TF module to create Datadog monitors based on resources tags ! I'm really happy to find it :)

My issue : 
I'm trying to use your module to create different monitors, but i noticed we can add tags (using "X_extra_tags" parameter), with the same name, but without the possibility to remove the default "team:claranet" tag or overwriting it, or I didn't find how to do it, can someone help me ? Or tell me what I missed :/

Example code, to reproduce :
```
module "datadog-monitors-cloud-aws-rds-common-xxx" {
  source  = "claranet/monitors/datadog//cloud/aws/rds/common" // AWS RDS PostgreSQL DB
  version = "4.6.0"

  environment = "PRD"
  prefix_slug = "ABC"
  message     = "test - message RDS alert"

  // filter_tags_custom 	Tags used for custom filtering when filter_tags_use_defaults is false 	string 	"*" 	no
  // filter_tags_custom_excluded 	Tags excluded for custom filtering when filter_tags_use_defaults is false 	string 	"" 	no
  // filter_tags_separator 	Set the filter tags separator (, or AND) 	string 	"," 	no
  filter_tags_use_defaults = false
  filter_tags_custom       = "name:xxx" // "team:ABC" OR "*"

  # CPU
  cpu_enabled            = true
  cpu_extra_tags         = ["team:ABC-ops", "service:subteam01"]
  cpu_message            = "cpu_message2"
  cpu_threshold_critical = "90" // CPU usage in percent (critical threshold)
  cpu_threshold_warning  = "80" // CPU usage in percent (warning threshold)
  # Diskspace
  diskspace_enabled            = true
  diskspace_extra_tags         = ["team:ABC-ops", "service:subteam01"]
  diskspace_message            = "diskspace_message"
  diskspace_threshold_critical = 10 // Disk free space in percent (critical threshold)
  diskspace_threshold_warning  = 20 // Disk free space in percent (warning threshold)
  diskspace_time_aggregator    = "min"
  diskspace_timeframe          = "last_5m"
  evaluation_delay             = 300
  # Replicalag
  replicalag_enabled    = false
  replicalag_extra_tags = ["team:ABC-ops", "service:subteam01"]
  # Connection Variance
  connection_variance_enabled    = false
  connection_variance_extra_tags = ["team:ABC-ops", "service:subteam01"]
}
```

With this code example, I can see this on Datadog Platform : 
![image](https://github.com/claranet/terraform-datadog-monitors/assets/8619233/a15b5fdd-dac5-4cb0-b7d1-0929e146cac0)

Do we have a way to simply get ride of this "team:claranet" tag to put our team tag instead ? :)

Thank you !

**Comment by BetterToAutomateTheWorld** [comment]
Hi all,

Any news on this issue ?

**Comment by vidarw** [comment]
@Aohzan @claranet We are prepared to help you with the Azure modules if this is an acceptable suggestion.

We think that all the default tags should be overridable. Our suggestion would be to move the set of default tags to a variable:

`["env:${var.environment}", "type:cloud", "provider:azure", "resource:app-gateway", "team:claranet", "created-by:terraform"]`

```
var default_tags {
   type = list(string)
   default = ["env:${var.environment}", "type:cloud", "provider:azure", "resource:app-gateway", "team:claranet", "created-by:terraform"]
}

#...
#in definitions:

tags = concat(var.default_tags, var.status_extra_tags)

```

Thoughts @BetterToAutomateTheWorld ?

**Comment by Aohzan** [comment]
hello, sorry I didn't this issue (thanks for the ping), I fix that

**Comment by Aohzan** [comment]
sorry for the time...it should be ok now, just set `ŧeam = "ABC-ops"`

**Comment by BetterToAutomateTheWorld** [comment]
@Aohzan Thank you very much for this 4.9.0 version with the team tag fix !

Your version 4.9.0 adds also the common locals/inputs, but i don't find any README about it, it seems my terraform init / plan are crashing on this new version, probably something i'm doing wrong : 
![image](https://github.com/claranet/terraform-datadog-monitors/assets/8619233/c8ad98c4-72e1-412f-bc9e-5a7f1887437c)

My deployment is as following : 
```
module "dd-monitors-dbxxxxxxx4508" {
  source  = "claranet/monitors/datadog//cloud/aws/rds/common"
  version = "4.9.0"

  environment              = "PRD - dbxxxxxxx4508" //  WTG Quant AWS PRD RDS (dbxxxxxxx4508) PostgreSQL DB
  prefix_slug              = "ABC"
  message                  = "message RDS alert"
  tags = [
    "type:cloud",
    "provider:aws",
    "resource:rds"
  ]
  team = "abc-ops"
  common_tags = ["env:PRD - xxx", "team:abc-ops", "created-by:terraform"]

  filter_tags_use_defaults = false
  filter_tags_custom       = "name:dbxxxxxxx4508" // "team:ABC" OR "*"
  // filter_tags_custom_excluded = ""	  // Tags excluded for custom filtering when filter_tags_use_defaults is false 	string 	"" 	no
  // filter_tags_separator = ""	        // Set the filter tags separator (, or AND) 	string 	"," 	no

  # Database Connection Anomaly
  connection_variance_enabled    = false
  connection_variance_extra_tags = ["team:abc-ops", "service:some-team"]
  connection_variance_message    = "Monitor triggered  \n  \n Notify : @teams-some-team-Data-Pipeline-Alerts"
  # CPU Utilization
  cpu_enabled            = true
  cpu_extra_tags         = ["team:abc-ops", "service:some-team"]
  cpu_message            = "Monitor triggered  \n  \n Notify : @teams-some-team-Data-Pipeline-Alerts"
  cpu_threshold_critical = "90" // CPU usage in percent (critical threshold)
  cpu_threshold_warning  = "70" // CPU usage in percent (warning threshold)
  # Storage Utilization
  diskspace_enabled            = true
  diskspace_extra_tags         = ["team:abc-ops", "service:some-team"]
  diskspace_message            = "Monitor triggered  \n  \n Notify : @teams-some-team-Data-Pipeline-Alerts"
  diskspace_threshold_critical = 10 // Disk free space in percent (critical threshold)
  diskspace_threshold_warning  = 20 // Disk free space in percent (warning threshold)
  diskspace_time_aggregator    = "min"
  diskspace_timeframe          = "last_5m"
  evaluation_delay             = 300
  # Replicalag (Only for Cluster type)
  replicalag_enabled = false
}
```

Do you have any idea how could I fixed this issue ?

**Comment by Aohzan** [comment]
are you on windows ? it looks like the symlink doesn't work :thinking: 

(you don't have to set the `common_tags` variable)

**Comment by BetterToAutomateTheWorld** [comment]
Yes, that's correct, as a testing purpose, i'm running a terraform init / plan / apply on this shitty OS (windows) :/

I can try with our GNU/Linux pipeline, but it means if 4.9.0 is used in our repository, all of our colleagues on Windows trying to run local TF deployment will be blocked :'(

**Comment by Aohzan** [comment]
can you run in WSL or in a container ?

**Comment by BetterToAutomateTheWorld** [comment]
Not possible in my company network/security policy, and even if it was, I'm not really sure i want to disrupt way of working for hundreds of people :/

**Comment by Aohzan** [comment]
I didn't find a way to solve this for Windows' users, except duplicate the file x times but it's not really acceptable
There is some "solution" online: https://stackoverflow.com/questions/5917249/git-symbolic-links-in-windows

Otherwise, if it's only to local testing, maybe you can script a copy from `common/module/inputs.tf` to every module directory you use ?

**Comment by BetterToAutomateTheWorld** [comment]
Yeah, none of the solutions are possible, or it's possible but extremely over complicated for something that simple as a symlink...

I guess we will stay on v4.8.0 and never move up, or choose another DD/Monitoring module if the tag is annoying us in the future (and i'm sad to say it 😢), It also means we can never move to 4.9.0 and above, to get new features/bugfixes, because local tests for 95% of our sandbox devs won't work anymore

Don't worry, it's not your fault here, it's this shitty OS (Windows), your new common module feature was great (even if it doesn't bring any big improvements in our case, and we wouldn't have used it)

**Comment by Aohzan** [comment]
try with `git clone -c core.symlinks=true https://github.com/claranet/terraform-datadog-monitors.git`

**Comment by Aohzan** [comment]
@BetterToAutomateTheWorld

**Comment by BetterToAutomateTheWorld** [comment]
Hi @Aohzan,

Sorry for my late answer ;

I don't know what you mean with this git clone command, we're using the module as direct remote source from terraform, using a module call similar to below : 

```
module "datadog-monitors-cloud-aws-rds-common-xxx" {
  source  = "claranet/monitors/datadog//cloud/aws/rds/common" // AWS RDS PostgreSQL DB
  version = "4.6.0"
  [...]
}
```

**Comment by BetterToAutomateTheWorld** [comment]
Hi @Aohzan,

Still not working following your instructions, and even following this step-by-step guide : https://devcoops.com/enable-symlinks-in-windows-vscode-git/

And i can follow these steps because i'm administrator (gitbash re-install with symlinks option checked, instead of using company store, etc.) on my Windows workstation, it's not the case for all of my coworkers... Again, it's a company laptop, i doubt this can be done in all companies...

 I started dropping your module since this morning for new Datadog interactions we needed, again, it's a shame...
 
 I appreciate you help and give us possible solutions even if it's not working in our side ! :)

**Comment by Lynggaard91** [comment]
Helloes! Just reopening this thread as the changes made to override the `team:claranet` tag for Datadog/Cloud/aws/rds/common has not been applied/fixed.

I have made a PR https://github.com/claranet/terraform-datadog-monitors/pull/54

@BetterToAutomateTheWorld hopefully this helps you too! :)
